version: '3.3'
services:
    linux-desktop:
        build:
            context: .
            dockerfile: Dockerfile
        image: debian-novnc
        container_name: debian-novnc
        environment:
          - TZ=Asia/Shanghai
        ports:
            - '5901:5901'
            - '6901:6901'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
